/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./apps/web/**/*.{js,ts,jsx,tsx,mdx}', './packages/ui/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        ide: {
          bg: 'var(--ide-color-bg)',
          panel: 'var(--ide-color-panel)',
          surface: 'var(--ide-color-surface)',
          elevated: 'var(--ide-color-elevated)',
          border: 'var(--ide-color-border)',
          'border-strong': 'var(--ide-color-border-strong)',
          'border-subtle': 'var(--ide-color-border-subtle)',
          'modal-border': 'var(--ide-color-modal-border)',
          text: 'var(--ide-color-text)',
          'text-strong': 'var(--ide-color-text-strong)',
          'text-high': 'var(--ide-color-text-high)',
          'body-text': 'var(--ide-color-body-text)',
          'text-secondary': 'var(--ide-color-text-secondary)',
          'text-body': 'var(--ide-color-text-body)',
          'text-soft': 'var(--ide-color-text-soft)',
          'text-dim': 'var(--ide-color-text-dim)',
          muted: 'var(--ide-color-muted)',
          subtle: 'var(--ide-color-subtle)',
          accent: 'var(--ide-color-accent)',
          'accent-fg': 'var(--ide-color-accent-fg)',
          'accent-soft': 'var(--ide-color-accent-soft)',
          secondary: 'var(--ide-color-secondary)',
          tertiary: 'var(--ide-color-tertiary)',
          'warm-accent': 'var(--ide-color-warm-accent)',
          danger: 'var(--ide-color-danger)',
          warning: 'var(--ide-color-warning)',
          success: 'var(--ide-color-success)',
          info: 'var(--ide-color-info)',
          hover: 'var(--ide-color-hover)',
          active: 'var(--ide-color-active)',
          'surface-overlay': 'var(--ide-color-surface-overlay)',
          'dropdown-bg': 'var(--ide-color-dropdown-bg)',
          'shell-bg': 'var(--ide-color-shell-bg)',
          'topbar-bg': 'var(--ide-color-topbar-bg)',
          'sidebar-surface': 'var(--ide-color-sidebar-surface)',
          'app-content-bg': 'var(--ide-color-app-content-bg)',
          'workbench-bg': 'var(--ide-color-workbench-bg)',
          'welcome-action-bg': 'var(--ide-color-welcome-action-bg)',
          'welcome-secondary-bg-start': 'var(--ide-color-welcome-secondary-bg-start)',
          'welcome-secondary-bg-end': 'var(--ide-color-welcome-secondary-bg-end)',
          'sidebar-footer-bg': 'var(--ide-color-sidebar-footer-bg)',
          'terminal-border': 'var(--ide-color-terminal-border)',
          'editor-line-highlight': 'var(--ide-color-editor-line-highlight)',
          'surface-raised': 'var(--ide-color-surface-raised)',
          'surface-hover': 'var(--ide-color-surface-hover)',
          'surface-hover-strong': 'var(--ide-color-surface-hover-strong)',
          'skeleton-mid': 'var(--ide-color-skeleton-mid)',
          'skeleton-strong': 'var(--ide-color-skeleton-strong)',
          overlay: 'var(--ide-color-overlay)',
          'shadow-color': 'var(--ide-color-shadow-color)',
          'shadow-active': 'var(--ide-color-shadow-active)',
          'shadow-shortcut': 'var(--ide-color-shadow-shortcut)',
          'shadow-panel': 'var(--ide-color-shadow-panel)',
          'shadow-account': 'var(--ide-color-shadow-account)',
          'shadow-card': 'var(--ide-color-shadow-card)',
          'shadow-card-hover': 'var(--ide-color-shadow-card-hover)',
          'shadow-strong': 'var(--ide-color-shadow-strong)',
          'input-bg': 'var(--ide-color-input-bg)',
          'input-border': 'var(--ide-color-input-border)',
          'tab-active': 'var(--ide-color-tab-active)',
          'tab-inactive': 'var(--ide-color-tab-inactive)',
          'statusbar-bg': 'var(--ide-color-statusbar-bg)',
          'statusbar-fg': 'var(--ide-color-statusbar-fg)',
          'sidebar-bg': 'var(--ide-color-sidebar-bg)',
          'editor-bg': 'var(--ide-color-editor-bg)',
          'gutter-fg': 'var(--ide-color-gutter-fg)',
          'accent-hover': 'var(--ide-color-accent-hover)',
          'accent-secondary': 'var(--ide-color-accent-secondary)',
          'focus-ring': 'var(--ide-color-focus-ring)',
          'scrollbar-hover': 'var(--ide-color-scrollbar-hover)',
          scrollbar: 'var(--ide-color-scrollbar)',
          selection: 'var(--ide-color-selection)',
          'surface-card': 'var(--ide-color-surface-card)',
          'surface-card-alt': 'var(--ide-color-surface-card-alt)',
          'surface-toolbar': 'var(--ide-color-surface-toolbar)',
          'surface-control': 'var(--ide-color-surface-control)',
          'surface-control-hover': 'var(--ide-color-surface-control-hover)',
          'surface-empty': 'var(--ide-color-surface-empty)',
          'surface-danger': 'var(--ide-color-surface-danger)',
          'border-control': 'var(--ide-color-border-control)',
          'border-danger': 'var(--ide-color-border-danger)',
          'text-tertiary': 'var(--ide-color-text-tertiary)',
          'text-quiet': 'var(--ide-color-text-quiet)',
          'text-faint': 'var(--ide-color-text-faint)',
          'text-placeholder': 'var(--ide-color-text-placeholder)',
          'text-danger-soft': 'var(--ide-color-text-danger-soft)',
          'repository-toolbar': 'var(--ide-color-repository-toolbar)',
          'repository-border': 'var(--ide-color-repository-border)',
          'repository-focus': 'var(--ide-color-repository-focus)',
          'workspace-surface': 'var(--ide-color-workspace-surface)',
          'workspace-border': 'var(--ide-color-workspace-border)',
          'workspace-border-inner': 'var(--ide-color-workspace-border-inner)'
        },
        devpulse: {
          purple: '#7C3AED',
          cyan: '#06B6D4',
          bg: '#0A0A0F',
          panel: '#111118',
          text: '#e8e8f0',
          muted: '#7a7a9a'
        }
      },
      fontFamily: {
        sans: ['Space Grotesk', 'ui-sans-serif', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace']
      }
    }
  },
  plugins: []
};
