"use client";

import React, { useState } from "react";
import { useApp } from "../context/AppContext";
import {
  Sparkles,
  Send,
  Copy,
  Check,
  Plus,
  ChevronDown,
  FileCode,
  Package,
  GitBranch,
  Lock,
  Cpu,
  Bot,
  Sliders,
  Code2,
  ArrowRight,
  ShieldCheck,
  RefreshCw,
  CornerDownLeft,
} from "lucide-react";

export const FullScreenAiPage: React.FC = () => {
  const { theme, user, setPage, applyDiffToActiveFile } = useApp();

  const [selectedModel, setSelectedModel] = useState("Claude Sonnet 4.6");
  const [temperature, setTemperature] = useState(0.2);
  const [topP, setTopP] = useState(0.95);
  const [copied, setCopied] = useState(false);
  const [applied, setApplied] = useState(true);
  const [inputQuery, setInputQuery] = useState("");
  const [isModelDropdownOpen, setIsModelDropdownOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const [chatMessages, setChatMessages] = useState([
    {
      id: 1,
      sender: "Alex R.",
      time: "11:24 AM",
      isUser: true,
      text: "Fix the authentication bug in my login.js file",
    },
    {
      id: 2,
      sender: "Devpulse Engine",
      model: "Claude Sonnet 4.6",
      time: "11:24 AM",
      isUser: false,
      text: "Identified the issue in login.js . The token verification promise was not properly awaited before setting the session cookie, resulting in an unhandled race condition where requests were rejected with 401 Unauthorized .",
      hasCode: true,
      codeFilename: "JavaScript - login.js",
      codeSnippet: `export async function handleLogin(req, res) {
  const { email, password } = req.body;
  const user = await authenticateUser(email, password);
  if (!user) throw new AuthError('Invalid credentials');

  // Await signed JWT token generation before session dispatch
  const sessionToken = await createSessionToken(user.id, { expiresIn: '7d' });
  res.setHeader('Set-Cookie', serializeCookie('cp_session', sessionToken, {
    httpOnly: true,
    secure: true
  }));
  return res.status(200).json({ success: true, user: sanitizeUser(user) });
}`,
      generationStats: "Generated in 1.4s · 320 tokens",
    },
  ]);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputQuery.trim()) return;

    const userMsg = {
      id: Date.now(),
      sender: user.name,
      time: "Just now",
      isUser: true,
      text: inputQuery.trim(),
    };

    setChatMessages((previous) => [...previous, userMsg]);
    setInputQuery("");
    setIsGenerating(true);
    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000"}/v1/ai/chat`,
        {
          method: "POST",
          credentials: "include",
          headers: { "Content-Type": "application/json", Accept: "text/event-stream" },
          body: JSON.stringify({
            messages: [
              {
                role: "user",
                content: `Project: auth-service\nActive file: src/auth/login.js\nBranch: fix/jwt-expiry\nModel preference: ${selectedModel}\nTemperature: ${temperature}\nTop-p: ${topP}\nRequest: ${userMsg.text}`,
              },
            ],
          }),
        },
      );
      if (!response.ok) {
        const result = (await response.json().catch(() => ({}))) as { error?: string };
        throw new Error(result.error || "AI request failed");
      }
      const reader = response.body?.getReader();
      if (!reader) throw new Error("AI service returned no response stream");
      const decoder = new TextDecoder();
      let buffer = "";
      let responseText = "";
      while (true) {
        const chunk = await reader.read();
        buffer += decoder.decode(chunk.value ?? new Uint8Array(), { stream: !chunk.done });
        const events = buffer.split("\n\n");
        buffer = events.pop() ?? "";
        for (const event of events) {
          const line = event.split("\n").find((value) => value.startsWith("data: "));
          if (!line) continue;
          const payload = JSON.parse(line.slice(6)) as { type?: string; content?: string; message?: string };
          if (payload.type === "chunk") responseText += payload.content ?? "";
          if (payload.type === "error") throw new Error(payload.message || "AI request failed");
        }
        if (chunk.done) break;
      }
      if (!responseText) responseText = "The AI returned no text.";
      const aiMsg = {
        id: Date.now() + 1,
        sender: "Devpulse Engine",
        model: selectedModel,
        time: "Just now",
        isUser: false,
        text: responseText,
        hasCode: false,
        codeFilename: "AI response",
        codeSnippet: responseText,
        generationStats: "Generated by AI service",
      };
      setChatMessages((previous) => [...previous, aiMsg]);
    } catch (error) {
      setChatMessages((previous) => [
        ...previous,
        {
          id: Date.now() + 1,
          sender: "Devpulse Engine",
          model: selectedModel,
          time: "Just now",
          isUser: false,
          text:
            error instanceof Error
              ? `AI error: ${error.message}`
              : "AI request failed",
          hasCode: false,
          codeFilename: "AI error",
          codeSnippet: "",
          generationStats: "Request failed",
        },
      ]);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyCode = (snippet: string) => {
    navigator.clipboard.writeText(snippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-[calc(100vh-3.5rem)] flex flex-col bg-[#09090e] text-[#d6d6e6] overflow-hidden font-sans select-none">
      {/* Top AI Studio Header (Pixel-Perfect to Screenshot 3) */}
      <div className="h-14 bg-[#0d0d15] border-b border-[#1c1c2b] px-5 flex items-center justify-between shrink-0 font-mono text-xs z-20">
        {/* Left: AI Assistant Version & Model Switcher */}
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <div
              className="w-6 h-6 rounded-lg flex items-center justify-center text-[#09090e]"
              style={{ backgroundColor: theme.primary }}
            >
              <Sparkles className="w-3.5 h-3.5" />
            </div>
            <span className="font-bold text-white text-sm">AI Assistant</span>
            <span className="px-2 py-0.5 rounded-full text-[10px] bg-[#0DF5C4]/15 border border-[#0DF5C4]/30 text-[#0DF5C4]">
              v4.4
            </span>
          </div>

          {/* Model Switcher Dropdown */}
          <div className="relative">
            <button
              onClick={() => setIsModelDropdownOpen(!isModelDropdownOpen)}
              className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-[#141420] hover:bg-[#1a1a2b] border border-[#242436] text-white transition-colors"
            >
              <span className="w-2 h-2 rounded-full bg-[#0DF5C4]" />
              <span className="font-bold">{selectedModel}</span>
              <span className="text-[10px] text-[#787896]">200k Context</span>
              <span className="px-1.5 py-0.5 rounded bg-[#0DF5C4]/10 text-[#0DF5C4] text-[9px] font-bold">
                Fast Inference
              </span>
              <ChevronDown className="w-3 h-3 text-[#787896]" />
            </button>

            {isModelDropdownOpen && (
              <div className="absolute left-0 mt-1.5 w-60 bg-[#12121c] border border-[#26263a] rounded-xl shadow-2xl py-1 z-50 text-xs font-mono">
                {[
                  "Claude Sonnet 4.6",
                  "GPT-4o (Omni Fast)",
                  "CodeLlama 70B (Local MicroVM)",
                ].map((m) => (
                  <button
                    key={m}
                    onClick={() => {
                      setSelectedModel(m);
                      setIsModelDropdownOpen(false);
                    }}
                    className="w-full text-left px-3 py-2 hover:bg-[#1a1a2a] text-white flex items-center justify-between"
                  >
                    <span>{m}</span>
                    {selectedModel === m && (
                      <Check className="w-3.5 h-3.5 text-[#0DF5C4]" />
                    )}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right: Hyperparameters & New Chat */}
        <div className="flex items-center gap-4 text-[#8b8ba8]">
          <div className="hidden lg:flex items-center gap-3">
            <span>
              Temp: <strong className="text-white">{temperature}</strong>
            </span>
            <span>·</span>
            <span>
              Top-p: <strong className="text-white">{topP}</strong>
            </span>
          </div>

          <div className="hidden sm:flex items-center gap-1.5 text-xs">
            <span className="text-white font-medium">3 active threads</span>
          </div>

          <button
            onClick={() => setChatMessages([])}
            className="px-3 py-1.5 rounded-xl bg-[#171724] hover:bg-[#202032] border border-[#2b2b40] text-white flex items-center gap-1.5 transition-colors"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>New Chat</span>
          </button>
        </div>
      </div>

      {/* Active Context Chips Bar (Pixel-Perfect to Screenshot 3) */}
      <div className="h-10 bg-[#0a0a10] border-b border-[#181824] px-5 flex items-center justify-between font-mono text-xs shrink-0 overflow-x-auto">
        <div className="flex items-center gap-3">
          <span className="text-[10px] text-[#63637e] uppercase tracking-wider">
            ACTIVE CONTEXT
          </span>

          <span className="px-2.5 py-1 rounded-lg bg-[#141420] border border-[#222232] text-[#c4c4dc] flex items-center gap-1.5">
            <FileCode className="w-3 h-3 text-[#3178c6]" />
            <span>src/auth/login.js</span>
          </span>

          <span className="px-2.5 py-1 rounded-lg bg-[#141420] border border-[#222232] text-[#0DF5C4] flex items-center gap-1.5">
            <Package className="w-3 h-3" />
            <span>auth-service</span>
          </span>

          <span className="px-2.5 py-1 rounded-lg bg-[#141420] border border-[#222232] text-[#FF9E64] flex items-center gap-1.5">
            <GitBranch className="w-3 h-3" />
            <span>fix/jwt-expiry</span>
          </span>
        </div>

        <div className="flex items-center gap-1.5 text-[#0DF5C4] text-[11px]">
          <span className="w-1.5 h-1.5 rounded-full bg-[#0DF5C4] animate-pulse" />
          <span>Context sync valid (1,480 tokens)</span>
        </div>
      </div>

      {/* Main Chat Conversation Area (Pixel-Perfect to Screenshot 3) */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6 max-w-4xl mx-auto w-full select-text">
        {chatMessages.map((msg) => (
          <div key={msg.id} className="space-y-3">
            {/* Message Header */}
            <div className="flex items-center justify-between text-xs font-mono">
              <div className="flex items-center gap-2">
                <span
                  className={`font-bold ${msg.isUser ? "text-white" : "text-[#b5afff]"}`}
                >
                  {msg.sender}
                </span>
                {!msg.isUser && (
                  <span className="px-2 py-0.5 rounded text-[10px] bg-[#6C63FF]/20 text-[#c8c4ff] border border-[#6C63FF]/40">
                    {msg.model}
                  </span>
                )}
              </div>
              <span className="text-[#656580] text-[11px]">{msg.time}</span>
            </div>

            {/* User message balloon */}
            {msg.isUser ? (
              <div className="p-4 rounded-2xl bg-[#141422] border border-[#242438] text-white text-sm leading-relaxed max-w-2xl ml-auto">
                {msg.text}
              </div>
            ) : (
              /* AI Response Container */
              <div className="bg-[#101018] border border-[#222232] rounded-2xl p-6 shadow-2xl space-y-4">
                <p className="text-xs sm:text-sm text-[#d0d0e4] leading-relaxed">
                  {msg.text}
                </p>

                {/* Embedded Syntax Highlighted Code Box */}
                {msg.hasCode && (
                  <div className="bg-[#09090f] border border-[#202030] rounded-xl overflow-hidden font-mono text-xs">
                    <div className="bg-[#13131f] px-4 py-2 border-b border-[#202030] flex items-center justify-between text-[11px]">
                      <div className="flex items-center gap-2 text-white font-medium">
                        <span className="w-2 h-2 rounded-full bg-[#0DF5C4]" />
                        <span>{msg.codeFilename}</span>
                      </div>

                      <div className="flex items-center gap-3 text-[#8b8ba8]">
                        <button
                          onClick={() => handleCopyCode(msg.codeSnippet!)}
                          className="hover:text-white flex items-center gap-1"
                        >
                          {copied ? (
                            <Check className="w-3.5 h-3.5 text-[#0DF5C4]" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                          <span>Copy</span>
                        </button>
                        <button
                          onClick={() => {
                            void applyDiffToActiveFile(
                              msg.codeSnippet || "",
                            ).then(() => {
                              setApplied(true);
                              setPage("editor");
                            });
                          }}
                          className="px-2.5 py-1 rounded-lg bg-[#6C63FF]/20 hover:bg-[#6C63FF]/30 text-white font-semibold flex items-center gap-1"
                        >
                          <span>Insert at Cursor</span>
                        </button>
                      </div>
                    </div>

                    <pre className="p-4 text-[#d6d6e8] leading-relaxed overflow-x-auto text-[11px]">
                      <code>{msg.codeSnippet}</code>
                    </pre>

                    <div className="px-4 py-2 bg-[#0d0d16] border-t border-[#1a1a28] flex items-center justify-between text-[11px] font-mono text-[#6c6c88]">
                      <span className="text-[#0DF5C4] flex items-center gap-1">
                        <Check className="w-3 h-3" /> Applied to login.js
                      </span>
                      <span>{msg.generationStats}</span>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
        {isGenerating && (
          <div className="text-xs font-mono text-[#0DF5C4]">
            Devpulse AI is generating...
          </div>
        )}
      </div>

      {/* Bottom AI Input Dock (Pixel-Perfect to Screenshot 3) */}
      <div className="p-4 bg-[#0d0d15] border-t border-[#1c1c2b] shrink-0">
        <div className="max-w-4xl mx-auto space-y-2">
          {/* Tagged Files Bar */}
          <div className="flex items-center gap-2 text-xs font-mono">
            <span className="px-2.5 py-1 rounded-lg bg-[#141422] border border-[#232338] text-[#3178c6] flex items-center gap-1">
              <FileCode className="w-3 h-3" /> @login.js
            </span>
            <span className="px-2.5 py-1 rounded-lg bg-[#141422] border border-[#232338] text-[#FF9E64] flex items-center gap-1">
              <Package className="w-3 h-3" /> @package.json
            </span>
            <button className="px-2 py-1 rounded-lg bg-[#141420] text-[#71718c] hover:text-white border border-transparent hover:border-[#2b2b3e]">
              + Add File
            </button>
          </div>

          {/* Prompt Form */}
          <form onSubmit={handleSend} className="relative">
            <input
              type="text"
              value={inputQuery}
              onChange={(e) => setInputQuery(e.target.value)}
              placeholder="Ask AI to write, fix, or explain code... (Use @ to tag files, / for commands)"
              className="w-full pl-4 pr-24 py-3.5 bg-[#12121e] border border-[#25253a] rounded-2xl text-xs text-white placeholder-[#585874] focus:outline-none focus:border-[#6C63FF] shadow-inner font-sans"
            />
            <button
              type="submit"
              className="absolute right-2.5 top-2.5 px-4 py-2 rounded-xl text-xs font-semibold text-[#09090e] flex items-center gap-1.5 shadow transition-all hover:brightness-110 active:scale-95"
              style={{ backgroundColor: theme.primary }}
            >
              <span>Send</span>
              <CornerDownLeft className="w-3.5 h-3.5 text-[#09090e]" />
            </button>
          </form>

          {/* Footer Telemetry & Security note */}
          <div className="flex items-center justify-between text-[11px] font-mono text-[#656582] px-1">
            <span>
              Press <strong>Return</strong> to send,{" "}
              <strong>Shift + Return</strong> for newline
            </span>
            <div className="flex items-center gap-4">
              <span>247 / 4,096 tokens</span>
              <span className="text-[#0DF5C4] flex items-center gap-1">
                <ShieldCheck className="w-3 h-3" />
                Enterprise Code Isolation Active
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
